apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      name: client
    - port: 27960
      targetPort: 27960
      nodePort: 30003
      name: server
    - port: 9090
      targetPort: 9090
      nodePort: 30002
      name: content
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    run: quake-kube
