/// Errors that can be generated by the controller.
#[derive(Debug, thiserror::Error)]
pub enum Error {
    /// Error when encoding a resource object.
    #[error("encoding error: {0}")]
    EncodingError(#[from] serde_json::Error),

    /// Error performing a kubernetes operation.
    #[error("kubernetes error: {0}")]
    KubeError(#[from] kube::Error),

    /// Error getting a cache node's state.
    #[error("node state error: {0}")]
    NodeStateError(Box<dyn std::error::Error + Send + Sync>),

    /// Error caused by an internal failure, this is almost certainly a bug.
    #[error("internal error: {0}")]
    InternalError(String),

    /// Error in user input or Echo resource definition, typically missing fields.
    #[error("Invalid Echo CRD: {0}")]
    UserInputError(String),

    #[error("Finalizer Error: {0}")]
    // NB: awkward type because finalizer::Error embeds the reconciler error (which is this)
    // so boxing this error to break cycles
    FinalizerError(#[source] Box<kube::runtime::finalizer::Error<Error>>),

    #[error("Failed to create ConfigMap: {0}")]
    ConfigMapCreationFailed(#[source] kube::Error),
    #[error("MissingObjectKey: {0}")]
    MissingObjectKey(&'static str),
}

impl Error {
    /// Create a new [Error::InternalError] with the provided message.
    pub fn internal(msg: &str) -> Self {
        Self::InternalError(String::from(msg))
    }
}

/// Result type for the controller.
pub type Result<T, E = Error> = std::result::Result<T, E>;
